version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blip-challenge
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
      HOST: "http://localhost"
      API_VERSION: "v1"
      PORT: 4000
      GITHUB_API_URL: 'https://api.github.com'
      ORG: 'takenet'
      LANGUAGE: 'C#'
    ports:
      - "4000:4000"
